# Set the base image to Ubuntu
FROM continuumio/miniconda3

# File Author / Maintainer
MAINTAINER Thomas Schmelzer "thomas.schmelzer@gmail.com"

RUN conda install -q -y pandas=0.18.1 scikit-learn nose coverage

# install the new cvxpy?
RUN conda install -y -c cvxgrp cvxpy

ADD ./cvxFin /cvxFin/cvxFin
ADD ./test   /cvxFin/test

WORKDIR cvxFin
