name: "ci"

# This workflow runs continuous integration tests
# It ensures the code works across different operating systems and Python versions

on:
- push  # Run workflow on every push to the repository

jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # Define the matrix of environments to test on
        os: [ ubuntu-latest, windows-latest, macos-latest ]  # Test on multiple operating systems
        python-version: [ '3.10', '3.11', '3.12', '3.13' ]  # Test on multiple Python versions

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Build the virtual environment for ${{ github.repository }}"
        uses: tschm/cradle/actions/environment@v0.1.57  # Set up Python environment with dependencies
        with:
          python-version: ${{ matrix.python-version }}  # Use Python version from matrix

      - uses: tschm/cradle/actions/test@v0.1.57  # Run tests with pytest
