name: Upload Python Package

on:
  workflow_run:
    workflows: ["Bump version"]
    types: [completed]

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: cvxgrp/.github/actions/uv/build@v2.0.7

  deploy:
    needs: build
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    environment: release

    permissions:
      id-token: write

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
